version: "3.8"

services:
  flask:
    build: .
    container_name: flask-app
    ports:
      - "4040:4040"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}


volumes:
  mysql-data:
